#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 492996-web-01 35.175.63.80 check
    server 492996-web-02 	52.91.183.235 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
